
pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = "False"  // Disable host key checking for Ansible
    }

    stages {
        stage('Run Ansible Playbook') {
            steps {
                sshagent(['private-key']) {
                    ansiblePlaybook(
                        become: true,
                        credentialsId: 'private-key',
                        installation: 'ansible',
                        inventory: "${WORKSPACE}/inventory/artifactory.yml",
                        playbook: "${WORKSPACE}/playbooks/site.yml"
                    )
                }
            }
        }
    }

    post {
        always {
            echo "Pipeline completed."
        }
    }
}
