pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    stages {
        stage('Initial cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main', url: 'https://github.com/mwangiii/ansible-config-mgt.git'
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}'
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
            }
        }

        stage('Install Artifactory on gcp-artifactory') {
            steps {
                sshagent(['private-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no njekev65@34.71.158.12 << 'EOF'
                        sudo sh -c 'echo "deb https://releases.jfrog.io/artifactory/artifactory-debs focal main" > /etc/apt/sources.list.d/jfrog-artifactory.list'
                        sudo apt update -y
                        sudo apt-get install jfrog-artifactory-oss -y
                    EOF
                    '''
                }
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }
    }
}
