---
- name: install apache
  become: true
  ansible.builtin.apt:
    name: "apache2"
    state: present
    update_cache: yes

- name: install git
  become: true
  ansible.builtin.apt:
    name: "git"
    state: present
    update_cache: yes

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/mwangiii/Tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  ansible.builtin.copy:
    src: /var/www/html/html/
    dest: /var/www/
    remote_src: yes

- name: Start service apache2, if not started
  become: true
  ansible.builtin.service:
    name: apache2
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent
