---
- name: Install JFrog Artifactory
  hosts: artifactory
  become: true
  tasks:
    - name: Set hostname to Artifactory
      ansible.builtin.hostname:
        name: Artifactory

    - name: Update Ubuntu OS
      ansible.builtin.apt:
        update_cache: yes

    - name: Add JFrog Artifactory APT repository
      ansible.builtin.apt_repository:
        repo: "deb https://releases.jfrog.io/artifactory/artifactory-debs xenial main"
        state: present
        filename: artifactory

    - name: Check if Artifactory GPG key already exists
      ansible.builtin.stat:
        path: /etc/apt/trusted.gpg.d/artifactory.gpg
      register: gpg_key

    - name: Import JFrog Artifactory GPG key
      ansible.builtin.shell: "curl -fsSL https://releases.jfrog.io/artifactory/api/gpg/key/public | gpg --dearmor -o /etc/apt/trusted.gpg.d/artifactory.gpg"
      when: not gpg_key.stat.exists

    - name: Update package cache after adding Artifactory repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install JFrog Artifactory OSS
      ansible.builtin.apt:
        name: jfrog-artifactory-oss
        state: present

    - name: Start Artifactory service
      ansible.builtin.service:
        name: artifactory.service
        state: started

    - name: Enable Artifactory service to start on boot
      ansible.builtin.systemd:
        name: artifactory.service
        enabled: yes

    - name: Check Artifactory service status
      ansible.builtin.service_facts:

    - name: Display Artifactory service status
      ansible.builtin.debug:
        msg: "{{ ansible_facts.services['artifactory.service'] }}"
