---
- name: Update and upgrade all Ubuntu servers
  hosts: all
  become: yes  # This will run the tasks as a superuser
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
